# Generated by Django 5.0.1 on 2024-01-31 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('pid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_tax', models.IntegerField()),
                ('amount_exc_tax', models.IntegerField()),
                ('contract_no', models.CharField(max_length=255)),
                ('contract_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('top', models.CharField(max_length=255)),
                ('sow', models.CharField(max_length=255)),
                ('oos', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('priority', models.CharField(choices=[('tinggi', 'Tinggi'), ('rendah', 'Rendah'), ('sedang', 'Sedang')], max_length=10)),
                ('type', models.CharField(max_length=255)),
                ('market_segment', models.CharField(max_length=255)),
                ('tech_use', models.TextField()),
                ('resiko', models.CharField(max_length=255)),
                ('completion_percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'db_table': 'apm_project',
                'ordering': ['-created_at'],
            },
        ),
    ]
