# Generated by Django 5.0.1 on 2024-02-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoices'},
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='apm_invoice',
        ),
    ]
