# Generated by Django 5.0.1 on 2024-02-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payments'},
        ),
        migrations.AlterModelTable(
            name='payment',
            table='apm_payment',
        ),
    ]
